name: Create Issue

on:
  push:
    branches: [ main ]
    paths:
      - 'PROJECT_ROADMAP.md'
      - '.github/workflows/create_issue.yml'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create Issue
      uses: actions/github-script@v6
      with:
        script: |
          const issueBody = `## Описание\nСоздание базового Telegram канала для взаимодействия с пользователями.\n\n## Цель\nОбеспечить базовое взаимодействие с пользователями через Telegram.\n\n## Требования\n- [ ] Создание канала в Telegram\n- [ ] Настройка базовых команд (/start, /help)\n- [ ] Настройка приветственного сообщения\n- [ ] Настройка базовых настроек канала\n\n## Технические детали\n- Файлы для изменения:\n  - \`src/bot/__init__.py\`\n  - \`src/bot/handlers.py\`\n  - \`src/bot/config.py\`\n  - \`requirements.txt\`\n\n## Критерии приемки\n- [ ] Канал создан и доступен\n- [ ] Работают базовые команды\n- [ ] Корректно отображается приветственное сообщение\n- [ ] Настройки канала соответствуют требованиям\n\n## Связанные компоненты\n- [ ] Telegram Bot API\n- [ ] База данных\n- [ ] Система логирования\n\n## Метрики успеха\n- [ ] Время ответа бота < 1 секунды\n- [ ] 100% доступность базовых команд\n- [ ] Корректная обработка ошибок\n- [ ] Логирование всех действий\n\n## Дополнительная информация\nЭтот issue является частью Этапа 1.2 "Базовая структура бота" согласно PROJECT_ROADMAP.md`;

          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '[TASK] Создание базового ТГ канала',
            body: issueBody,
            labels: ['task', 'telegram', 'bot']
          });
          
          const project = await github.rest.projects.listForOrg({
            org: context.repo.owner
          });
          
          if (project.data.length > 0) {
            await github.rest.projects.createCard({
              project_id: project.data[0].id,
              content_id: issue.data.id,
              content_type: 'Issue'
            });
          } 