name: Deploy to VPS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install FreeRDP
      run: choco install freerdp -y
    
    - name: Deploy via RDP
      env:
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      run: |
        $SecurePassword = ConvertTo-SecureString "$env:RDP_PASSWORD" -AsPlainText -Force
        $Credential = New-Object System.Management.Automation.PSCredential ("AdmVps", $SecurePassword)
        
        # Настраиваем параметры RDP
        $ComputerName = "65.21.73.61"
        $Port = 3389
        
        # Копируем файл через RDP
        $Session = New-PSSession -ComputerName $ComputerName -Port $Port -Credential $Credential -Authentication Negotiate
        Copy-Item "test_deploy.py" -Destination "C:\Users\AdmVps\DualAI\" -ToSession $Session -Force
        
        # Запускаем тест
        Invoke-Command -Session $Session -ScriptBlock {
          Set-Location "C:\Users\AdmVps\DualAI"
          python test_deploy.py
        }
        
        Remove-PSSession $Session 